export type TypographyAlign = 'left' | 'center' | 'right' | 'inherit' | 'justify'

export type TypographyVariants = 'title'
  | 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'h5'
  | 'h6'
  | 'p'
  | 'text'
  | 'link'

export type TypographyType = 'default'
  | 'secondary'
  | 'success'
  | 'warning'
  | 'danger'
  | 'disabled'
  | 'underline'
  | 'delete'
  | 'strong'
  | 'italic'
